package:
    name: sdt-python
    version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}{{ '.post' + environ.get('GIT_DESCRIBE_NUMBER', "0") if environ.get('GIT_DESCRIBE_NUMBER', "0") != "0" else ''}}

source:
    git_url: ../

build:
    number: 0
    script: python setup.py install

requirements:
    build:
        - nomkl  # [unix]
        - python
        - setuptools
        - numpy >=1.10
        - pandas
        - pytables
        - scipy
        - tifffile >=0.7.0
        - pyyaml
        - pims >=0.3.0
        - slicerator >=0.9.7
        - qtpy >=1.1
        - matplotlib
        - lmfit
        - pywavelets >=0.3.0

    run:
        - python
        - numpy
        - pandas
        - pytables
        - scipy
        - tifffile
        - pyyaml
        - pims >=0.3.0
        - slicerator >=0.9.7
        - numba
        - qtpy >=1.1
        - matplotlib
        - lmfit
        - pywavelets >=0.3.0

test:
    requires:
        - nomkl  # [unix]
        - nose

    commands:
        - nosetests -v

    source_files:
        - tests

about:
    summary: "Tools related to fluorescence microscopy"

