package:
    name: sdt-python
    version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}{{ '.post' + environ.get('GIT_DESCRIBE_NUMBER', "0") if environ.get('GIT_DESCRIBE_NUMBER', "0") != "0" else ''}}

source:
    git_url: ../

build:
    number: 0
    script: python setup.py install
    noarch: python

requirements:
    host:
        - nomkl  # [unix]
        - python
        - setuptools
        - numpy >=1.10
        - pandas
        - pytables
        - scipy >0.18
        - tifffile >=0.14.0
        - pyyaml
        - pims >=0.3.0
        - qtpy >=1.1
        - matplotlib
        - pywavelets >=0.3.0
        - micro-helpers >=0.7

    run:
        - python
        - numpy >=1.10
        - pandas
        - pytables
        - scipy >0.18
        - tifffile >=0.14.0
        - pyyaml
        - pims >=0.3.0
        - numba
        - qtpy >=1.1
        - matplotlib
        - pywavelets >=0.3.0
        - micro-helpers >=0.7

test:
    requires:
        - nomkl  # [unix]
        - pytest
        - trackpy
        - lmfit

    commands:
        - pytest -v tests

    source_files:
        - tests

about:
    summary: "Tools related to fluorescence microscopy"

