package:
    name: sdt-python
    version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}{{ '.post' + environ.get('GIT_DESCRIBE_NUMBER', "0") if environ.get('GIT_DESCRIBE_NUMBER', "0") != "0" else ''}}

source:
    git_url: ../

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"
    noarch: python

requirements:
    host:
        - nomkl  # [unix]
        - python
        - setuptools
        - numpy >=1.10
        - pandas
        - pytables
        - scipy >0.18
        - tifffile >=0.14.0
        - pyyaml
        - pims >=0.3.0
        - qtpy >=1.1
        - matplotlib
        - pywavelets >=0.3.0
        - pip

    run:
        - python
        - numpy >=1.10
        - pandas
        - pytables
        - scipy >0.18
        - tifffile >=0.14.0
        - pyyaml
        - pims >=0.3.0
        - numba
        - qtpy >=1.1
        - matplotlib
        - pywavelets >=0.3.0

test:
    requires:
        - nomkl  # [unix]
        - pytest
        - trackpy
        - lmfit
        - pandas <1.0

    commands:
        - pytest -v tests

    source_files:
        - tests

about:
    summary: "Tools related to fluorescence microscopy"

